// World English Bible, public domain. Source: https://ebible.org/engwebp/copyright.htm
// Generated by scripts/import-faith-verses.py; source wording preserved, whitespace normalized.
export const FAITH_VERSES = Object.freeze([
  {
    "reference": "Psalms 23:1",
    "text": "The LORD is my shepherd; I shall lack nothing.",
    "source": "https://ebible.org/engwebp/PSA023.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 23:2",
    "text": "He makes me lie down in green pastures. He leads me beside still waters.",
    "source": "https://ebible.org/engwebp/PSA023.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 23:3",
    "text": "He restores my soul. He guides me in the paths of righteousness for his name’s sake.",
    "source": "https://ebible.org/engwebp/PSA023.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 23:4",
    "text": "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.",
    "source": "https://ebible.org/engwebp/PSA023.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 23:5",
    "text": "You prepare a table before me in the presence of my enemies. You anoint my head with oil. My cup runs over.",
    "source": "https://ebible.org/engwebp/PSA023.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 23:6",
    "text": "Surely goodness and loving kindness shall follow me all the days of my life, and I will dwell in the LORD’s house forever.",
    "source": "https://ebible.org/engwebp/PSA023.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 121:1",
    "text": "I will lift up my eyes to the hills. Where does my help come from?",
    "source": "https://ebible.org/engwebp/PSA121.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 121:2",
    "text": "My help comes from the LORD, who made heaven and earth.",
    "source": "https://ebible.org/engwebp/PSA121.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 121:3",
    "text": "He will not allow your foot to be moved. He who keeps you will not slumber.",
    "source": "https://ebible.org/engwebp/PSA121.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 121:4",
    "text": "Behold, he who keeps Israel will neither slumber nor sleep.",
    "source": "https://ebible.org/engwebp/PSA121.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 121:5",
    "text": "The LORD is your keeper. The LORD is your shade on your right hand.",
    "source": "https://ebible.org/engwebp/PSA121.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 121:6",
    "text": "The sun will not harm you by day, nor the moon by night.",
    "source": "https://ebible.org/engwebp/PSA121.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 121:7",
    "text": "The LORD will keep you from all evil. He will keep your soul.",
    "source": "https://ebible.org/engwebp/PSA121.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 121:8",
    "text": "The LORD will keep your going out and your coming in, from this time forward, and forever more.",
    "source": "https://ebible.org/engwebp/PSA121.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:4",
    "text": "Love is patient and is kind. Love doesn’t envy. Love doesn’t brag, is not proud,",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:11",
    "text": "When I was a child, I spoke as a child, I felt as a child, I thought as a child. Now that I have become a man, I have put away childish things.",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:12",
    "text": "For now we see in a mirror, dimly, but then face to face. Now I know in part, but then I will know fully, even as I was also fully known.",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:13",
    "text": "But now faith, hope, and love remain—these three. The greatest of these is love.",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:4",
    "text": "Rejoice in the Lord always! Again I will say, “Rejoice!”",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:5",
    "text": "Let your gentleness be known to all men. The Lord is at hand.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:6",
    "text": "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:7",
    "text": "And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:8",
    "text": "Finally, brothers, whatever things are true, whatever things are honorable, whatever things are just, whatever things are pure, whatever things are lovely, whatever things are of good report: if there is any virtue and if there is anything worthy of praise, think about these things.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:9",
    "text": "Do the things which you learned, received, heard, and saw in me, and the God of peace will be with you.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:13",
    "text": "I can do all things through Christ who strengthens me.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:19",
    "text": "My God will supply every need of yours according to his riches in glory in Christ Jesus.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 1:1",
    "text": "Blessed is the man who doesn’t walk in the counsel of the wicked, nor stand on the path of sinners, nor sit in the seat of scoffers;",
    "source": "https://ebible.org/engwebp/PSA001.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:1",
    "text": "The heavens declare the glory of God. The expanse shows his handiwork.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:1",
    "text": "The LORD is my light and my salvation. Whom shall I fear? The LORD is the strength of my life. Of whom shall I be afraid?",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:1",
    "text": "I will bless the LORD at all times. His praise will always be in my mouth.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:1",
    "text": "God is our refuge and strength, a very present help in trouble.",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:1",
    "text": "He who dwells in the secret place of the Most High will rest in the shadow of the Almighty.",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 100:1",
    "text": "Shout for joy to the LORD, all you lands!",
    "source": "https://ebible.org/engwebp/PSA100.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:1",
    "text": "Praise the LORD, my soul! All that is within me, praise his holy name!",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:1",
    "text": "LORD, you have searched me, and you know me.",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:1",
    "text": "I will exalt you, my God, the King. I will praise your name forever and ever.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 150:1",
    "text": "Praise the LORD! Praise God in his sanctuary! Praise him in his heavens for his acts of power!",
    "source": "https://ebible.org/engwebp/PSA150.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:1",
    "text": "My son, don’t forget my teaching, but let your heart keep my commandments,",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:1",
    "text": "The plans of the heart belong to man, but the answer of the tongue is from the LORD.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:1",
    "text": "“Comfort, comfort my people,” says your God.",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:1",
    "text": "“Hey! Come, everyone who thirsts, to the waters! Come, he who has no money, buy, and eat! Yes, come, buy wine and milk without money and without price.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:1",
    "text": "Seeing the multitudes, he went up onto the mountain. When he had sat down, his disciples came to him.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:1",
    "text": "“Be careful that you don’t do your charitable giving before men, to be seen by them, or else you have no reward from your Father who is in heaven.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:1",
    "text": "“Don’t judge, so that you won’t be judged.",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:1",
    "text": "“Don’t let your heart be troubled. Believe in God. Believe also in me.",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:1",
    "text": "“I am the true vine, and my Father is the farmer.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:1",
    "text": "There is therefore now no condemnation to those who are in Christ Jesus, who don’t walk according to the flesh, but according to the Spirit.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:1",
    "text": "Therefore I urge you, brothers, by the mercies of God, to present your bodies a living sacrifice, holy, acceptable to God, which is your spiritual service.",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:1",
    "text": "If I speak with the languages of men and of angels, but don’t have love, I have become sounding brass or a clanging cymbal.",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:1",
    "text": "Stand firm therefore in the liberty by which Christ has made us free, and don’t be entangled again with a yoke of bondage.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:1",
    "text": "I therefore, the prisoner in the Lord, beg you to walk worthily of the calling with which you were called,",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:1",
    "text": "If therefore there is any exhortation in Christ, if any consolation of love, if any fellowship of the Spirit, if any tender mercies and compassion,",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:1",
    "text": "Therefore, my brothers, beloved and longed for, my joy and crown, stand firm in the Lord in this way, my beloved.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:1",
    "text": "If then you were raised together with Christ, seek the things that are above, where Christ is, seated on the right hand of God.",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:1",
    "text": "James, a servant of God and of the Lord Jesus Christ, to the twelve tribes which are in the Dispersion: Greetings.",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:1",
    "text": "Therefore, since Christ suffered for us in the flesh, arm yourselves also with the same mind; for he who has suffered in the flesh has ceased from sin,",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:1",
    "text": "Beloved, don’t believe every spirit, but test the spirits, whether they are of God, because many false prophets have gone out into the world.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 1:2",
    "text": "but his delight is in the LORD’s law. On his law he meditates day and night.",
    "source": "https://ebible.org/engwebp/PSA001.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:2",
    "text": "Day after day they pour out speech, and night after night they display knowledge.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:2",
    "text": "When evildoers came at me to eat up my flesh, even my adversaries and my foes, they stumbled and fell.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:2",
    "text": "My soul shall boast in the LORD. The humble shall hear of it and be glad.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:2",
    "text": "Therefore we won’t be afraid, though the earth changes, though the mountains are shaken into the heart of the seas;",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:2",
    "text": "I will say of the LORD, “He is my refuge and my fortress; my God, in whom I trust.”",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 100:2",
    "text": "Serve the LORD with gladness. Come before his presence with singing.",
    "source": "https://ebible.org/engwebp/PSA100.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:2",
    "text": "Praise the LORD, my soul, and don’t forget all his benefits,",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:2",
    "text": "You know my sitting down and my rising up. You perceive my thoughts from afar.",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:2",
    "text": "Every day I will praise you. I will extol your name forever and ever.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 150:2",
    "text": "Praise him for his mighty acts! Praise him according to his excellent greatness!",
    "source": "https://ebible.org/engwebp/PSA150.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:2",
    "text": "for they will add to you length of days, years of life, and peace.",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:2",
    "text": "All the ways of a man are clean in his own eyes, but the LORD weighs the motives.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:2",
    "text": "“Speak comfortably to Jerusalem, and call out to her that her warfare is accomplished, that her iniquity is pardoned, that she has received of the LORD’s hand double for all her sins.”",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:2",
    "text": "Why do you spend money for that which is not bread, and your labor for that which doesn’t satisfy? Listen diligently to me, and eat that which is good, and let your soul delight itself in richness.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:2",
    "text": "He opened his mouth and taught them, saying,",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:2",
    "text": "Therefore, when you do merciful deeds, don’t sound a trumpet before yourself, as the hypocrites do in the synagogues and in the streets, that they may get glory from men. Most certainly I tell you, they have received their reward.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:2",
    "text": "For with whatever judgment you judge, you will be judged; and with whatever measure you measure, it will be measured to you.",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:2",
    "text": "In my Father’s house are many homes. If it weren’t so, I would have told you. I am going to prepare a place for you.",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:2",
    "text": "Every branch in me that doesn’t bear fruit, he takes away. Every branch that bears fruit, he prunes, that it may bear more fruit.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:2",
    "text": "For the law of the Spirit of life in Christ Jesus made me free from the law of sin and of death.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:2",
    "text": "Don’t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:2",
    "text": "If I have the gift of prophecy, and know all mysteries and all knowledge, and if I have all faith, so as to remove mountains, but don’t have love, I am nothing.",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:2",
    "text": "Behold, I, Paul, tell you that if you receive circumcision, Christ will profit you nothing.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:2",
    "text": "with all lowliness and humility, with patience, bearing with one another in love,",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:2",
    "text": "make my joy full by being like-minded, having the same love, being of one accord, of one mind;",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:2",
    "text": "I exhort Euodia, and I exhort Syntyche, to think the same way in the Lord.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:2",
    "text": "Set your mind on the things that are above, not on the things that are on the earth.",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:2",
    "text": "Count it all joy, my brothers, when you fall into various temptations,",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:2",
    "text": "that you no longer should live the rest of your time in the flesh for the lusts of men, but for the will of God.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:2",
    "text": "By this you know the Spirit of God: every spirit who confesses that Jesus Christ has come in the flesh is of God,",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 1:3",
    "text": "He will be like a tree planted by the streams of water, that produces its fruit in its season, whose leaf also does not wither. Whatever he does shall prosper.",
    "source": "https://ebible.org/engwebp/PSA001.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:3",
    "text": "There is no speech nor language where their voice is not heard.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:3",
    "text": "Though an army should encamp against me, my heart shall not fear. Though war should rise against me, even then I will be confident.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:3",
    "text": "Oh magnify the LORD with me. Let’s exalt his name together.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:3",
    "text": "though its waters roar and are troubled, though the mountains tremble with their swelling. Selah.",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:3",
    "text": "For he will deliver you from the snare of the fowler, and from the deadly pestilence.",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 100:3",
    "text": "Know that the LORD, he is God. It is he who has made us, and we are his. We are his people, and the sheep of his pasture.",
    "source": "https://ebible.org/engwebp/PSA100.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:3",
    "text": "who forgives all your sins, who heals all your diseases,",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:3",
    "text": "You search out my path and my lying down, and are acquainted with all my ways.",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:3",
    "text": "Great is the LORD, and greatly to be praised! His greatness is unsearchable.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 150:3",
    "text": "Praise him with the sounding of the trumpet! Praise him with harp and lyre!",
    "source": "https://ebible.org/engwebp/PSA150.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:3",
    "text": "Don’t let kindness and truth forsake you. Bind them around your neck. Write them on the tablet of your heart.",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:3",
    "text": "Commit your deeds to the LORD, and your plans shall succeed.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:3",
    "text": "The voice of one who calls out, “Prepare the way of the LORD in the wilderness! Make a level highway in the desert for our God.",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:3",
    "text": "Turn your ear, and come to me. Hear, and your soul will live. I will make an everlasting covenant with you, even the sure mercies of David.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:3",
    "text": "“Blessed are the poor in spirit, for theirs is the Kingdom of Heaven.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:3",
    "text": "But when you do merciful deeds, don’t let your left hand know what your right hand does,",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:3",
    "text": "Why do you see the speck that is in your brother’s eye, but don’t consider the beam that is in your own eye?",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:3",
    "text": "If I go and prepare a place for you, I will come again and will receive you to myself; that where I am, you may be there also.",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:3",
    "text": "You are already pruned clean because of the word which I have spoken to you.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:3",
    "text": "For what the law couldn’t do, in that it was weak through the flesh, God did, sending his own Son in the likeness of sinful flesh and for sin, he condemned sin in the flesh,",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:3",
    "text": "For I say through the grace that was given me, to everyone who is among you, not to think of yourself more highly than you ought to think; but to think reasonably, as God has apportioned to each person a measure of faith.",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:3",
    "text": "If I give away all my goods to feed the poor, and if I give my body to be burned, but don’t have love, it profits me nothing.",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:3",
    "text": "Yes, I testify again to every man who receives circumcision that he is a debtor to do the whole law.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:3",
    "text": "being eager to keep the unity of the Spirit in the bond of peace.",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:3",
    "text": "doing nothing through rivalry or through conceit, but in humility, each counting others better than himself;",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:3",
    "text": "Yes, I beg you also, true partner, help these women, for they labored with me in the Good News with Clement also, and the rest of my fellow workers, whose names are in the book of life.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:3",
    "text": "For you died, and your life is hidden with Christ in God.",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:3",
    "text": "knowing that the testing of your faith produces endurance.",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:3",
    "text": "For we have spent enough of our past time doing the desire of the Gentiles, and having walked in lewdness, lusts, drunken binges, orgies, carousings, and abominable idolatries.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:3",
    "text": "and every spirit who doesn’t confess that Jesus Christ has come in the flesh is not of God; and this is the spirit of the Antichrist, of whom you have heard that it comes. Now it is in the world already.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 1:4",
    "text": "The wicked are not so, but are like the chaff which the wind drives away.",
    "source": "https://ebible.org/engwebp/PSA001.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:4",
    "text": "Their voice has gone out through all the earth, their words to the end of the world. In them he has set a tent for the sun,",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:4",
    "text": "One thing I have asked of the LORD, that I will seek after: that I may dwell in the LORD’s house all the days of my life, to see the LORD’s beauty, and to inquire in his temple.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:4",
    "text": "I sought the LORD, and he answered me, and delivered me from all my fears.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:4",
    "text": "There is a river, the streams of which make the city of God glad, the holy place of the tents of the Most High.",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:4",
    "text": "He will cover you with his feathers. Under his wings you will take refuge. His faithfulness is your shield and rampart.",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 100:4",
    "text": "Enter into his gates with thanksgiving, and into his courts with praise. Give thanks to him, and bless his name.",
    "source": "https://ebible.org/engwebp/PSA100.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:4",
    "text": "who redeems your life from destruction, who crowns you with loving kindness and tender mercies,",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:4",
    "text": "For there is not a word on my tongue, but behold, LORD, you know it altogether.",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:4",
    "text": "One generation will commend your works to another, and will declare your mighty acts.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 150:4",
    "text": "Praise him with tambourine and dancing! Praise him with stringed instruments and flute!",
    "source": "https://ebible.org/engwebp/PSA150.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:4",
    "text": "So you will find favor, and good understanding in the sight of God and man.",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:4",
    "text": "The LORD has made everything for its own end— yes, even the wicked for the day of evil.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:4",
    "text": "Every valley shall be exalted, and every mountain and hill shall be made low. The uneven shall be made level, and the rough places a plain.",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:4",
    "text": "Behold, I have given him for a witness to the peoples, a leader and commander to the peoples.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:4",
    "text": "Blessed are those who mourn, for they shall be comforted.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:4",
    "text": "so that your merciful deeds may be in secret, then your Father who sees in secret will reward you openly.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:4",
    "text": "Or how will you tell your brother, ‘Let me remove the speck from your eye,’ and behold, the beam is in your own eye?",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:4",
    "text": "You know where I go, and you know the way.”",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:4",
    "text": "Remain in me, and I in you. As the branch can’t bear fruit by itself unless it remains in the vine, so neither can you, unless you remain in me.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:4",
    "text": "that the ordinance of the law might be fulfilled in us who don’t walk according to the flesh, but according to the Spirit.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:4",
    "text": "For even as we have many members in one body, and all the members don’t have the same function,",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:4",
    "text": "You are alienated from Christ, you who desire to be justified by the law. You have fallen away from grace.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:4",
    "text": "There is one body and one Spirit, even as you also were called in one hope of your calling,",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:4",
    "text": "each of you not just looking to his own things, but each of you also to the things of others.",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:4",
    "text": "When Christ, our life, is revealed, then you will also be revealed with him in glory.",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:4",
    "text": "Let endurance have its perfect work, that you may be perfect and complete, lacking in nothing.",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:4",
    "text": "They think it is strange that you don’t run with them into the same excess of riot, speaking evil of you.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:4",
    "text": "You are of God, little children, and have overcome them, because greater is he who is in you than he who is in the world.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 1:5",
    "text": "Therefore the wicked shall not stand in the judgment, nor sinners in the congregation of the righteous.",
    "source": "https://ebible.org/engwebp/PSA001.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:5",
    "text": "which is as a bridegroom coming out of his room, like a strong man rejoicing to run his course.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:5",
    "text": "For in the day of trouble, he will keep me secretly in his pavilion. In the secret place of his tabernacle, he will hide me. He will lift me up on a rock.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:5",
    "text": "They looked to him, and were radiant. Their faces shall never be covered with shame.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:5",
    "text": "God is within her. She shall not be moved. God will help her at dawn.",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:5",
    "text": "You shall not be afraid of the terror by night, nor of the arrow that flies by day,",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 100:5",
    "text": "For the LORD is good. His loving kindness endures forever, his faithfulness to all generations.",
    "source": "https://ebible.org/engwebp/PSA100.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:5",
    "text": "who satisfies your desire with good things, so that your youth is renewed like the eagle’s.",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:5",
    "text": "You hem me in behind and before. You laid your hand on me.",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:5",
    "text": "I will meditate on the glorious majesty of your honor, on your wondrous works.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 150:5",
    "text": "Praise him with loud cymbals! Praise him with resounding cymbals!",
    "source": "https://ebible.org/engwebp/PSA150.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:5",
    "text": "Trust in the LORD with all your heart, and don’t lean on your own understanding.",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:5",
    "text": "Everyone who is proud in heart is an abomination to the LORD; they shall certainly not be unpunished.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:5",
    "text": "The LORD’s glory shall be revealed, and all flesh shall see it together; for the mouth of the LORD has spoken it.”",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:5",
    "text": "Behold, you shall call a nation that you don’t know; and a nation that didn’t know you shall run to you, because of the LORD your God, and for the Holy One of Israel; for he has glorified you.”",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:5",
    "text": "Blessed are the gentle, for they shall inherit the earth.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:5",
    "text": "“When you pray, you shall not be as the hypocrites, for they love to stand and pray in the synagogues and in the corners of the streets, that they may be seen by men. Most certainly, I tell you, they have received their reward.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:5",
    "text": "You hypocrite! First remove the beam out of your own eye, and then you can see clearly to remove the speck out of your brother’s eye.",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:5",
    "text": "Thomas said to him, “Lord, we don’t know where you are going. How can we know the way?”",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:5",
    "text": "I am the vine. You are the branches. He who remains in me and I in him bears much fruit, for apart from me you can do nothing.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:5",
    "text": "For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the Spirit, the things of the Spirit.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:5",
    "text": "so we, who are many, are one body in Christ, and individually members of one another,",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:5",
    "text": "doesn’t behave itself inappropriately, doesn’t seek its own way, is not provoked, takes no account of evil;",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:5",
    "text": "For we through the Spirit, by faith wait for the hope of righteousness.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:5",
    "text": "one Lord, one faith, one baptism,",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:5",
    "text": "Have this in your mind, which was also in Christ Jesus,",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:5",
    "text": "Put to death therefore your members which are on the earth: sexual immorality, uncleanness, depraved passion, evil desire, and covetousness, which is idolatry.",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:5",
    "text": "But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him.",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:5",
    "text": "They will give account to him who is ready to judge the living and the dead.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:5",
    "text": "They are of the world. Therefore they speak of the world, and the world hears them.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 1:6",
    "text": "For the LORD knows the way of the righteous, but the way of the wicked shall perish.",
    "source": "https://ebible.org/engwebp/PSA001.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:6",
    "text": "His going out is from the end of the heavens, his circuit to its ends. There is nothing hidden from its heat.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:6",
    "text": "Now my head will be lifted up above my enemies around me. I will offer sacrifices of joy in his tent. I will sing, yes, I will sing praises to the LORD.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:6",
    "text": "This poor man cried, and the LORD heard him, and saved him out of all his troubles.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:6",
    "text": "The nations raged. The kingdoms were moved. He lifted his voice and the earth melted.",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:6",
    "text": "nor of the pestilence that walks in darkness, nor of the destruction that wastes at noonday.",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:6",
    "text": "The LORD executes righteous acts, and justice for all who are oppressed.",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:6",
    "text": "This knowledge is beyond me. It’s lofty. I can’t attain it.",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:6",
    "text": "Men will speak of the might of your awesome acts. I will declare your greatness.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 150:6",
    "text": "Let everything that has breath praise the LORD! Praise the LORD!",
    "source": "https://ebible.org/engwebp/PSA150.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:6",
    "text": "In all your ways acknowledge him, and he will make your paths straight.",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:6",
    "text": "By mercy and truth iniquity is atoned for. By the fear of the LORD men depart from evil.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:6",
    "text": "The voice of one saying, “Cry out!” One said, “What shall I cry?” “All flesh is like grass, and all its glory is like the flower of the field.",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:6",
    "text": "Seek the LORD while he may be found. Call on him while he is near.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:6",
    "text": "Blessed are those who hunger and thirst for righteousness, for they shall be filled.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:6",
    "text": "But you, when you pray, enter into your inner room, and having shut your door, pray to your Father who is in secret; and your Father who sees in secret will reward you openly.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:6",
    "text": "“Don’t give that which is holy to the dogs, neither throw your pearls before the pigs, lest perhaps they trample them under their feet, and turn and tear you to pieces.",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:6",
    "text": "Jesus said to him, “I am the way, the truth, and the life. No one comes to the Father, except through me.",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:6",
    "text": "If a man doesn’t remain in me, he is thrown out as a branch and is withered; and they gather them, throw them into the fire, and they are burned.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:6",
    "text": "For the mind of the flesh is death, but the mind of the Spirit is life and peace;",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:6",
    "text": "having gifts differing according to the grace that was given to us: if prophecy, let’s prophesy according to the proportion of our faith;",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:6",
    "text": "doesn’t rejoice in unrighteousness, but rejoices with the truth;",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:6",
    "text": "For in Christ Jesus neither circumcision nor uncircumcision amounts to anything, but faith working through love.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:6",
    "text": "one God and Father of all, who is over all and through all and in us all.",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:6",
    "text": "who, existing in the form of God, didn’t consider equality with God a thing to be grasped,",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:6",
    "text": "For these things’ sake the wrath of God comes on the children of disobedience.",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:6",
    "text": "But let him ask in faith, without any doubting, for he who doubts is like a wave of the sea, driven by the wind and tossed.",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:6",
    "text": "For to this end the Good News was preached even to the dead, that they might be judged indeed as men in the flesh, but live as to God in the spirit.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:6",
    "text": "We are of God. He who knows God listens to us. He who is not of God doesn’t listen to us. By this we know the spirit of truth, and the spirit of error.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:7",
    "text": "The LORD’s law is perfect, restoring the soul. The LORD’s covenant is sure, making wise the simple.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:7",
    "text": "Hear, LORD, when I cry with my voice. Have mercy also on me, and answer me.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:7",
    "text": "The LORD’s angel encamps around those who fear him, and delivers them.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:7",
    "text": "The LORD of Armies is with us. The God of Jacob is our refuge. Selah.",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:7",
    "text": "A thousand may fall at your side, and ten thousand at your right hand; but it will not come near you.",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:7",
    "text": "He made known his ways to Moses, his deeds to the children of Israel.",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:7",
    "text": "Where could I go from your Spirit? Or where could I flee from your presence?",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:7",
    "text": "They will utter the memory of your great goodness, and will sing of your righteousness.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:7",
    "text": "Don’t be wise in your own eyes. Fear the LORD, and depart from evil.",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:7",
    "text": "When a man’s ways please the LORD, he makes even his enemies to be at peace with him.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:7",
    "text": "The grass withers, the flower fades, because the LORD’s breath blows on it. Surely the people are like grass.",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:7",
    "text": "Let the wicked forsake his way, and the unrighteous man his thoughts. Let him return to the LORD, and he will have mercy on him, to our God, for he will freely pardon.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:7",
    "text": "Blessed are the merciful, for they shall obtain mercy.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:7",
    "text": "In praying, don’t use vain repetitions as the Gentiles do; for they think that they will be heard for their much speaking.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:7",
    "text": "“Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you.",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:7",
    "text": "If you had known me, you would have known my Father also. From now on, you know him and have seen him.”",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:7",
    "text": "If you remain in me, and my words remain in you, you will ask whatever you desire, and it will be done for you.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:7",
    "text": "because the mind of the flesh is hostile toward God, for it is not subject to God’s law, neither indeed can it be.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:7",
    "text": "or service, let’s give ourselves to service; or he who teaches, to his teaching;",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:7",
    "text": "bears all things, believes all things, hopes all things, and endures all things.",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:7",
    "text": "You were running well! Who interfered with you that you should not obey the truth?",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:7",
    "text": "But to each one of us, the grace was given according to the measure of the gift of Christ.",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:7",
    "text": "but emptied himself, taking the form of a servant, being made in the likeness of men.",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:7",
    "text": "You also once walked in those, when you lived in them,",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:7",
    "text": "For that man shouldn’t think that he will receive anything from the Lord.",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:7",
    "text": "But the end of all things is near. Therefore be of sound mind, self-controlled, and sober in prayer.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:7",
    "text": "Beloved, let’s love one another, for love is of God; and everyone who loves has been born of God and knows God.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:8",
    "text": "The LORD’s precepts are right, rejoicing the heart. The LORD’s commandment is pure, enlightening the eyes.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:8",
    "text": "When you said, “Seek my face,” my heart said to you, “I will seek your face, LORD.”",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:8",
    "text": "Oh taste and see that the LORD is good. Blessed is the man who takes refuge in him.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:8",
    "text": "Come, see the LORD’s works, what desolations he has made on the earth.",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:8",
    "text": "You will only look with your eyes, and see the recompense of the wicked.",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:8",
    "text": "The LORD is merciful and gracious, slow to anger, and abundant in loving kindness.",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:8",
    "text": "If I ascend up into heaven, you are there. If I make my bed in Sheol, behold, you are there!",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:8",
    "text": "The LORD is gracious, merciful, slow to anger, and of great loving kindness.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:8",
    "text": "It will be health to your body, and nourishment to your bones.",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:8",
    "text": "Better is a little with righteousness, than great revenues with injustice.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:8",
    "text": "The grass withers, the flower fades; but the word of our God stands forever.”",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:8",
    "text": "“For my thoughts are not your thoughts, and your ways are not my ways,” says the LORD.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:8",
    "text": "Blessed are the pure in heart, for they shall see God.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:8",
    "text": "Therefore don’t be like them, for your Father knows what things you need before you ask him.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:8",
    "text": "For everyone who asks receives. He who seeks finds. To him who knocks it will be opened.",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:8",
    "text": "Philip said to him, “Lord, show us the Father, and that will be enough for us.”",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:8",
    "text": "“In this my Father is glorified, that you bear much fruit; and so you will be my disciples.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:8",
    "text": "Those who are in the flesh can’t please God.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:8",
    "text": "or he who exhorts, to his exhorting; he who gives, let him do it with generosity; he who rules, with diligence; he who shows mercy, with cheerfulness.",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:8",
    "text": "Love never fails. But where there are prophecies, they will be done away with. Where there are various languages, they will cease. Where there is knowledge, it will be done away with.",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:8",
    "text": "This persuasion is not from him who calls you.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:8",
    "text": "Therefore he says, “When he ascended on high, he led captivity captive, and gave gifts to people.”",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:8",
    "text": "And being found in human form, he humbled himself, becoming obedient to the point of death, yes, the death of the cross.",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:8",
    "text": "but now you must put them all away: anger, wrath, malice, slander, and shameful speaking out of your mouth.",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:8",
    "text": "He is a double-minded man, unstable in all his ways.",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:8",
    "text": "And above all things be earnest in your love among yourselves, for love covers a multitude of sins.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:8",
    "text": "He who doesn’t love doesn’t know God, for God is love.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:9",
    "text": "The fear of the LORD is clean, enduring forever. The LORD’s ordinances are true, and righteous altogether.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:9",
    "text": "Don’t hide your face from me. Don’t put your servant away in anger. You have been my help. Don’t abandon me, neither forsake me, God of my salvation.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:9",
    "text": "Oh fear the LORD, you his saints, for there is no lack with those who fear him.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:9",
    "text": "He makes wars cease to the end of the earth. He breaks the bow, and shatters the spear. He burns the chariots in the fire.",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:9",
    "text": "Because you have made the LORD your refuge, and the Most High your dwelling place,",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:9",
    "text": "He will not always accuse; neither will he stay angry forever.",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:9",
    "text": "If I take the wings of the dawn, and settle in the uttermost parts of the sea,",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:9",
    "text": "The LORD is good to all. His tender mercies are over all his works.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:9",
    "text": "Honor the LORD with your substance, with the first fruits of all your increase;",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:9",
    "text": "A man’s heart plans his course, but the LORD directs his steps.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:9",
    "text": "You who tell good news to Zion, go up on a high mountain. You who tell good news to Jerusalem, lift up your voice with strength! Lift it up! Don’t be afraid! Say to the cities of Judah, “Behold, your God!”",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:9",
    "text": "“For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:9",
    "text": "Blessed are the peacemakers, for they shall be called children of God.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:9",
    "text": "Pray like this: “ ‘Our Father in heaven, may your name be kept holy.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:9",
    "text": "Or who is there among you who, if his son asks him for bread, will give him a stone?",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:9",
    "text": "Jesus said to him, “Have I been with you such a long time, and do you not know me, Philip? He who has seen me has seen the Father. How do you say, ‘Show us the Father’?",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:9",
    "text": "Even as the Father has loved me, I also have loved you. Remain in my love.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:9",
    "text": "But you are not in the flesh but in the Spirit, if it is so that the Spirit of God dwells in you. But if any man doesn’t have the Spirit of Christ, he is not his.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:9",
    "text": "Let love be without hypocrisy. Abhor that which is evil. Cling to that which is good.",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:9",
    "text": "For we know in part and we prophesy in part;",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:9",
    "text": "A little yeast grows through the whole lump.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:9",
    "text": "Now this, “He ascended”, what is it but that he also first descended into the lower parts of the earth?",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:9",
    "text": "Therefore God also highly exalted him, and gave to him the name which is above every name,",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:9",
    "text": "Don’t lie to one another, seeing that you have put off the old man with his doings,",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:9",
    "text": "Let the brother in humble circumstances glory in his high position;",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:9",
    "text": "Be hospitable to one another without grumbling.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:9",
    "text": "By this God’s love was revealed in us, that God has sent his only born Son into the world that we might live through him.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:10",
    "text": "They are more to be desired than gold, yes, than much fine gold, sweeter also than honey and the extract of the honeycomb.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:10",
    "text": "When my father and my mother forsake me, then the LORD will take me up.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:10",
    "text": "The young lions do lack, and suffer hunger, but those who seek the LORD shall not lack any good thing.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:10",
    "text": "“Be still, and know that I am God. I will be exalted among the nations. I will be exalted on the earth.”",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:10",
    "text": "no evil shall happen to you, neither shall any plague come near your dwelling.",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:10",
    "text": "He has not dealt with us according to our sins, nor repaid us for our iniquities.",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:10",
    "text": "even there your hand will lead me, and your right hand will hold me.",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:10",
    "text": "All your works will give thanks to you, LORD. Your saints will extol you.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:10",
    "text": "so your barns will be filled with plenty, and your vats will overflow with new wine.",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:10",
    "text": "Inspired judgments are on the lips of the king. He shall not betray his mouth.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:10",
    "text": "Behold, the Lord GOD will come as a mighty one, and his arm will rule for him. Behold, his reward is with him, and his recompense before him.",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:10",
    "text": "For as the rain comes down and the snow from the sky, and doesn’t return there, but waters the earth, and makes it grow and bud, and gives seed to the sower and bread to the eater;",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:10",
    "text": "Blessed are those who have been persecuted for righteousness’ sake, for theirs is the Kingdom of Heaven.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:10",
    "text": "Let your Kingdom come. Let your will be done on earth as it is in heaven.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:10",
    "text": "Or if he asks for a fish, who will give him a serpent?",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:10",
    "text": "Don’t you believe that I am in the Father, and the Father in me? The words that I tell you, I speak not from myself; but the Father who lives in me does his works.",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:10",
    "text": "If you keep my commandments, you will remain in my love, even as I have kept my Father’s commandments and remain in his love.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:10",
    "text": "If Christ is in you, the body is dead because of sin, but the spirit is alive because of righteousness.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:10",
    "text": "In love of the brothers be tenderly affectionate to one another; in honor prefer one another,",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Corinthians 13:10",
    "text": "but when that which is complete has come, then that which is partial will be done away with.",
    "source": "https://ebible.org/engwebp/1CO13.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:10",
    "text": "I have confidence toward you in the Lord that you will think no other way. But he who troubles you will bear his judgment, whoever he is.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:10",
    "text": "He who descended is the one who also ascended far above all the heavens, that he might fill all things.",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:10",
    "text": "that at the name of Jesus every knee should bow, of those in heaven, those on earth, and those under the earth,",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:10",
    "text": "But I rejoice in the Lord greatly that now at length you have revived your thought for me; in which you did indeed take thought, but you lacked opportunity.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:10",
    "text": "and have put on the new man, who is being renewed in knowledge after the image of his Creator,",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:10",
    "text": "and the rich, in that he is made humble, because like the flower in the grass, he will pass away.",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:10",
    "text": "As each has received a gift, employ it in serving one another, as good managers of the grace of God in its various forms.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:10",
    "text": "In this is love, not that we loved God, but that he loved us, and sent his Son as the atoning sacrifice for our sins.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:11",
    "text": "Moreover your servant is warned by them. In keeping them there is great reward.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:11",
    "text": "Teach me your way, LORD. Lead me in a straight path, because of my enemies.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:11",
    "text": "Come, you children, listen to me. I will teach you the fear of the LORD.",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 46:11",
    "text": "The LORD of Armies is with us. The God of Jacob is our refuge. Selah.",
    "source": "https://ebible.org/engwebp/PSA046.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:11",
    "text": "For he will put his angels in charge of you, to guard you in all your ways.",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:11",
    "text": "For as the heavens are high above the earth, so great is his loving kindness toward those who fear him.",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:11",
    "text": "If I say, “Surely the darkness will overwhelm me. The light around me will be night,”",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:11",
    "text": "They will speak of the glory of your kingdom, and talk about your power,",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:11",
    "text": "My son, don’t despise the LORD’s discipline, neither be weary of his correction;",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:11",
    "text": "Honest balances and scales are the LORD’s; all the weights in the bag are his work.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:11",
    "text": "He will feed his flock like a shepherd. He will gather the lambs in his arm, and carry them in his bosom. He will gently lead those who have their young.",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:11",
    "text": "so is my word that goes out of my mouth: it will not return to me void, but it will accomplish that which I please, and it will prosper in the thing I sent it to do.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:11",
    "text": "“Blessed are you when people reproach you, persecute you, and say all kinds of evil against you falsely, for my sake.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:11",
    "text": "Give us today our daily bread.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:11",
    "text": "If you then, being evil, know how to give good gifts to your children, how much more will your Father who is in heaven give good things to those who ask him!",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:11",
    "text": "Believe me that I am in the Father, and the Father in me; or else believe me for the very works’ sake.",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:11",
    "text": "I have spoken these things to you, that my joy may remain in you, and that your joy may be made full.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:11",
    "text": "But if the Spirit of him who raised up Jesus from the dead dwells in you, he who raised up Christ Jesus from the dead will also give life to your mortal bodies through his Spirit who dwells in you.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:11",
    "text": "not lagging in diligence, fervent in spirit, serving the Lord,",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:11",
    "text": "But I, brothers, if I still preach circumcision, why am I still persecuted? Then the stumbling block of the cross has been removed.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:11",
    "text": "He gave some to be apostles; and some, prophets; and some, evangelists; and some, shepherds and teachers;",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:11",
    "text": "and that every tongue should confess that Jesus Christ is Lord, to the glory of God the Father.",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:11",
    "text": "Not that I speak because of lack, for I have learned in whatever state I am, to be content in it.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Colossians 3:11",
    "text": "where there can’t be Greek and Jew, circumcision and uncircumcision, barbarian, Scythian, bondservant, or free person; but Christ is all, and in all.",
    "source": "https://ebible.org/engwebp/COL03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "James 1:11",
    "text": "For the sun arises with the scorching wind and withers the grass; and the flower in it falls, and the beauty of its appearance perishes. So the rich man will also fade away in his pursuits.",
    "source": "https://ebible.org/engwebp/JAS01.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 Peter 4:11",
    "text": "If anyone speaks, let it be as it were the very words of God. If anyone serves, let it be as of the strength which God supplies, that in all things God may be glorified through Jesus Christ, to whom belong the glory and the dominion forever and ever. Amen.",
    "source": "https://ebible.org/engwebp/1PE04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "1 John 4:11",
    "text": "Beloved, if God loved us in this way, we also ought to love one another.",
    "source": "https://ebible.org/engwebp/1JN04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 19:12",
    "text": "Who can discern his errors? Forgive me from hidden errors.",
    "source": "https://ebible.org/engwebp/PSA019.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 27:12",
    "text": "Don’t deliver me over to the desire of my adversaries, for false witnesses have risen up against me, such as breathe out cruelty.",
    "source": "https://ebible.org/engwebp/PSA027.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 34:12",
    "text": "Who is someone who desires life, and loves many days, that he may see good?",
    "source": "https://ebible.org/engwebp/PSA034.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 91:12",
    "text": "They will bear you up in their hands, so that you won’t dash your foot against a stone.",
    "source": "https://ebible.org/engwebp/PSA091.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 103:12",
    "text": "As far as the east is from the west, so far has he removed our transgressions from us.",
    "source": "https://ebible.org/engwebp/PSA103.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 139:12",
    "text": "even the darkness doesn’t hide from you, but the night shines as the day. The darkness is like light to you.",
    "source": "https://ebible.org/engwebp/PSA139.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Psalms 145:12",
    "text": "to make known to the sons of men his mighty acts, the glory of the majesty of his kingdom.",
    "source": "https://ebible.org/engwebp/PSA145.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 3:12",
    "text": "for whom the LORD loves, he corrects, even as a father reproves the son in whom he delights.",
    "source": "https://ebible.org/engwebp/PRO03.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Proverbs 16:12",
    "text": "It is an abomination for kings to do wrong, for the throne is established by righteousness.",
    "source": "https://ebible.org/engwebp/PRO16.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 40:12",
    "text": "Who has measured the waters in the hollow of his hand, and marked off the sky with his span, and calculated the dust of the earth in a measuring basket, and weighed the mountains in scales, and the hills in a balance?",
    "source": "https://ebible.org/engwebp/ISA40.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Isaiah 55:12",
    "text": "For you shall go out with joy, and be led out with peace. The mountains and the hills will break out before you into singing; and all the trees of the fields will clap their hands.",
    "source": "https://ebible.org/engwebp/ISA55.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 5:12",
    "text": "Rejoice, and be exceedingly glad, for great is your reward in heaven. For that is how they persecuted the prophets who were before you.",
    "source": "https://ebible.org/engwebp/MAT05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 6:12",
    "text": "Forgive us our debts, as we also forgive our debtors.",
    "source": "https://ebible.org/engwebp/MAT06.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Matthew 7:12",
    "text": "Therefore, whatever you desire for men to do to you, you shall also do to them; for this is the law and the prophets.",
    "source": "https://ebible.org/engwebp/MAT07.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 14:12",
    "text": "Most certainly I tell you, he who believes in me, the works that I do, he will do also; and he will do greater works than these, because I am going to my Father.",
    "source": "https://ebible.org/engwebp/JHN14.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "John 15:12",
    "text": "“This is my commandment, that you love one another, even as I have loved you.",
    "source": "https://ebible.org/engwebp/JHN15.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 8:12",
    "text": "So then, brothers, we are debtors, not to the flesh, to live after the flesh.",
    "source": "https://ebible.org/engwebp/ROM08.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Romans 12:12",
    "text": "rejoicing in hope, enduring in troubles, continuing steadfastly in prayer,",
    "source": "https://ebible.org/engwebp/ROM12.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Galatians 5:12",
    "text": "I wish that those who disturb you would cut themselves off.",
    "source": "https://ebible.org/engwebp/GAL05.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Ephesians 4:12",
    "text": "for the perfecting of the saints, to the work of serving, to the building up of the body of Christ,",
    "source": "https://ebible.org/engwebp/EPH04.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 2:12",
    "text": "So then, my beloved, even as you have always obeyed, not only in my presence, but now much more in my absence, work out your own salvation with fear and trembling.",
    "source": "https://ebible.org/engwebp/PHP02.htm",
    "translation": "World English Bible"
  },
  {
    "reference": "Philippians 4:12",
    "text": "I know how to be humbled, and I also know how to abound. In any and all circumstances I have learned the secret both to be filled and to be hungry, both to abound and to be in need.",
    "source": "https://ebible.org/engwebp/PHP04.htm",
    "translation": "World English Bible"
  }
].map(verse => Object.freeze(verse)));
