// Stable IDs keep saved collections valid when display copy changes.
export const FOOD_RARITIES = Object.freeze([
  { id: 'common', label: 'Common', chance: 70 },
  { id: 'rare', label: 'Rare', chance: 22 },
  { id: 'epic', label: 'Epic', chance: 7 },
  { id: 'legendary', label: 'Legendary', chance: 1 },
]);
const rows = [
  ['pizza', '🍕', 'Pizza slice', 'common', 'Mostly cheese. An excellent decision.'],
  ['apple', '🍎', 'Apple', 'common', 'A crisp bite. Somewhere, a doctor checks their calendar.'],
  ['toast', '🍞', 'Toast', 'common', 'Bread went to the spa and came back crunchy.'],
  ['cookie', '🍪', 'Cookie', 'common', 'You promised to have just one. The crumbs disagree.'],
  ['fries', '🍟', 'Fries', 'common', 'You found the extra-crispy one at the bottom. Victory.'],
  ['banana', '🍌', 'Banana', 'common', 'Nature packed your snack in its own wrapper.'],
  ['rice', '🍚', 'Rice bowl', 'common', 'Simple, warm, and absolutely carrying the meal.'],
  ['sandwich', '🥪', 'Sandwich', 'common', 'Two slices of bread holding your afternoon together.'],
  ['carrot', '🥕', 'Carrot', 'common', 'Maximum crunch. Everyone in voice chat heard it.'],
  ['popcorn', '🍿', 'Popcorn', 'common', 'The snack is ready. Now you just need some harmless drama.'],
  ['pretzel', '🥨', 'Pretzel', 'common', 'A delicious knot. You decided not to untie it.'],
  ['ice', '🧊', 'Ice cube', 'common', 'Congratulations. You have successfully chewed water.'],
  ['sushi', '🍣', 'Sushi', 'rare', 'A tiny work of art. You ate the exhibition.'],
  ['taco', '🌮', 'Taco', 'rare', 'The first bite was perfect. The second became a salad.'],
  ['ramen', '🍜', 'Ramen', 'rare', 'One noodle escaped. The rest were delicious.'],
  ['donut', '🍩', 'Galaxy donut', 'rare', 'The sprinkles look like stars. You ate a small universe.'],
  ['dumpling', '🥟', 'Dumpling', 'rare', 'A little pocket of happiness. No zipper required.'],
  ['waffle', '🧇', 'Waffle tower', 'rare', 'Every square holds syrup and a tiny architectural achievement.'],
  ['cake', '🍰', 'Cloud cake', 'epic', 'So fluffy you checked whether gravity was still enabled.'],
  ['curry', '🍛', 'Dragon curry', 'epic', 'Your character breathed imaginary fire. The bowl looks proud.'],
  ['mushroom', '🍄', 'Glowing mushroom', 'epic', 'A fictional dungeon snack. Your character now has mood lighting.'],
  ['icecream', '🍨', 'Aurora sundae', 'epic', 'Three flavors, seven colors, and one very confused spoon.'],
  ['burger', '🍔', 'Golden burger', 'legendary', 'The dungeon chef bows. You ask if it comes with fries.'],
  ['feast', '🍱', 'Dexzu feast', 'legendary', 'The rarest lunch in the dungeon. Even the final boss wants a bite.'],
  ['pear', '🍐', 'Pear', 'common', 'A sweet snack with excellent posture.'],
  ['orange', '🍊', 'Orange', 'common', 'You won the battle against the peel.'],
  ['grapes', '🍇', 'Grapes', 'common', 'Tiny snacks conveniently arranged in a squad.'],
  ['watermelon', '🍉', 'Watermelon', 'common', 'A refreshing slice with built-in seed surprises.'],
  ['strawberry', '🍓', 'Strawberry', 'common', 'Small fruit. Huge main-character energy.'],
  ['cherries', '🍒', 'Cherries', 'common', 'Two bites, one very happy snack break.'],
  ['peach', '🍑', 'Peach', 'common', 'Juice has officially reached your sleeve.'],
  ['pineapple', '🍍', 'Pineapple', 'common', 'The snack arrived wearing a crown.'],
  ['mango', '🥭', 'Mango', 'common', 'Your afternoon now tastes like a holiday.'],
  ['kiwi', '🥝', 'Kiwi', 'common', 'Fuzzy outside, tiny fireworks inside.'],
  ['melon', '🍈', 'Melon', 'common', 'A cool bite for a very busy adventurer.'],
  ['blueberries', '🫐', 'Blueberries', 'common', 'You ate a handful of tiny blue treasures.'],
  ['coconut', '🥥', 'Coconut', 'common', 'The hardest part was opening the packaging.'],
  ['cucumber', '🥒', 'Cucumber', 'common', 'Crunchy water has entered the chat.'],
  ['tomato', '🍅', 'Tomato', 'common', 'Fruit or vegetable? Lunch refuses to debate.'],
  ['corn', '🌽', 'Corn cob', 'common', 'You cleared every row like a professional.'],
  ['potato', '🥔', 'Baked potato', 'common', 'Warm, dependable, and wearing a butter hat.'],
  ['broccoli', '🥦', 'Broccoli', 'common', 'You have eaten an extremely small forest.'],
  ['peas', '🫛', 'Peas', 'common', 'One rolled away. The others accepted their fate.'],
  ['avocado', '🥑', 'Avocado toast', 'common', 'The toast has upgraded its lifestyle.'],
  ['bagel', '🥯', 'Bagel', 'common', 'The missing middle remains a mystery.'],
  ['croissant', '🥐', 'Croissant', 'common', 'Flaky pastry, now distributed across your keyboard.'],
  ['baguette', '🥖', 'Baguette', 'common', 'Lunch is unusually long today.'],
  ['cheese', '🧀', 'Cheese wedge', 'common', 'A sharp choice for a snack.'],
  ['egg', '🥚', 'Boiled egg', 'common', 'Simple protein. Surprisingly dramatic peeling.'],
  ['pancake', '🥞', 'Pancakes', 'common', 'You ordered breakfast and received a stack.'],
  ['cereal', '🥣', 'Cereal bowl', 'common', 'You finished before the crunch timer expired.'],
  ['salad', '🥗', 'Garden salad', 'common', 'Every leaf attended the lunch meeting.'],
  ['soup', '🥣', 'Tomato soup', 'common', 'A warm bowl of take-it-easy.'],
  ['hotdog', '🌭', 'Hot dog', 'common', 'The mustard took the scenic route.'],
  ['cracker', '🍘', 'Rice cracker', 'common', 'One bite announced itself to the whole room.'],
  ['chocolate', '🍫', 'Chocolate bar', 'common', 'You saved a square for later. Briefly.'],
  ['candy', '🍬', 'Fruit candy', 'common', 'The wrapper was louder than the snack.'],
  ['lollipop', '🍭', 'Lollipop', 'common', 'A snack with a convenient carrying handle.'],
  ['cupcake', '🧁', 'Cupcake', 'common', 'A personal cake with no sharing negotiations.'],
  ['peanuts', '🥜', 'Roasted peanuts', 'common', 'A handful turned into a very generous handful.'],
  ['burrito', '🌯', 'Burrito', 'rare', 'A delicious blanket holding everything together.'],
  ['falafel', '🧆', 'Falafel pita', 'rare', 'Crispy little heroes, safely tucked in pita.'],
  ['hummus', '🥣', 'Hummus plate', 'rare', 'The pita volunteered for one more dip.'],
  ['shakshuka', '🍳', 'Shakshuka', 'rare', 'Breakfast brought its own bubbling sauce.'],
  ['shawarma', '🥙', 'Shawarma', 'rare', 'You caught the escaping filling. Legendary reflexes.'],
  ['gyros', '🥙', 'Gyros', 'rare', 'A wrapped lunch with serious holiday energy.'],
  ['kebab', '🍢', 'Grilled kebab', 'rare', 'The grill marks spell delicious. Probably.'],
  ['pierogi', '🥟', 'Pierogi', 'rare', 'Little dumplings with very big comfort energy.'],
  ['bao', '🥟', 'Steamed bao', 'rare', 'A soft bun guarding a tasty secret.'],
  ['bibimbap', '🍚', 'Bibimbap', 'rare', 'You mixed the colors into a masterpiece.'],
  ['kimchi', '🥬', 'Kimchi', 'rare', 'Your taste buds have started a lively discussion.'],
  ['padthai', '🍜', 'Pad Thai', 'rare', 'The noodles have excellent teamwork.'],
  ['pho', '🍜', 'Pho', 'rare', 'The steam smells like a very good decision.'],
  ['udon', '🍜', 'Udon', 'rare', 'Thick noodles. Extremely serious slurping.'],
  ['onigiri', '🍙', 'Onigiri', 'rare', 'A rice triangle has joined your party.'],
  ['tempura', '🍤', 'Tempura', 'rare', 'The crunch deserves its own sound effect.'],
  ['takoyaki', '🍢', 'Takoyaki', 'rare', 'Small, round, and absolutely worth the wait.'],
  ['paella', '🥘', 'Paella', 'rare', 'A whole celebration arrived in one pan.'],
  ['risotto', '🍚', 'Risotto', 'rare', 'Every grain received personal attention.'],
  ['lasagna', '🍝', 'Lasagna', 'rare', 'You discovered another layer of happiness.'],
  ['gnocchi', '🥔', 'Gnocchi', 'rare', 'Potatoes learned how to become tiny pillows.'],
  ['ravioli', '🍝', 'Ravioli', 'rare', 'Pasta parcels. All addressed to you.'],
  ['empanada', '🥟', 'Empanada', 'rare', 'A golden pastry keeping lunch confidential.'],
  ['arepa', '🫓', 'Arepa', 'rare', 'The crispy outside made an excellent introduction.'],
  ['samosa', '🥟', 'Samosa', 'rare', 'Three corners, zero regrets.'],
  ['biryani', '🍛', 'Biryani', 'rare', 'Your ordinary rice bowl is taking notes.'],
  ['tiramisu', '🍰', 'Tiramisu', 'rare', 'Dessert brought a tiny coffee break.'],
  ['baklava', '🍯', 'Baklava', 'rare', 'Flaky, sweet, and determined to stick around.'],
  ['mochi', '🍡', 'Mochi', 'rare', 'A tiny dessert with impressive bounce.'],
  ['churros', '🥖', 'Churros', 'rare', 'Cinnamon sugar has claimed your fingertips.'],
  ['moonpie', '🥧', 'Moon pie', 'epic', 'The fictional moon bakery sends its regards.'],
  ['starpasta', '🍝', 'Starlight pasta', 'epic', 'Your fork twirled a tiny constellation.'],
  ['phoenixtaco', '🌮', 'Phoenix taco', 'epic', 'An imaginary fiery taco. The napkin looks nervous.'],
  ['frostberry', '🫐', 'Frost berries', 'epic', 'A fantasy snack with a personal snow forecast.'],
  ['rainbowsushi', '🍣', 'Rainbow sushi', 'epic', 'The chef used the entire color palette.'],
  ['crystalcandy', '🍬', 'Crystal candy', 'epic', 'Edible fantasy gems. The goblins look jealous.'],
  ['cometcrepe', '🥞', 'Comet crepe', 'epic', 'Dessert arrived ahead of its own sparkle trail.'],
  ['nebularamen', '🍜', 'Nebula ramen', 'epic', 'An imaginary galaxy swirls in your soup.'],
  ['elfbread', '🍞', 'Elven bread', 'epic', 'The fantasy baker included a polite woodland bow.'],
  ['wizardwaffle', '🧇', 'Wizard waffle', 'epic', 'It cast syrup. A very practical spell.'],
  ['mermaidmacaron', '🍪', 'Mermaid macaron', 'epic', 'A fictional ocean bakery packed a sweet surprise.'],
  ['thunderpopcorn', '🍿', 'Thunder popcorn', 'epic', 'Every imaginary kernel brought a drum solo.'],
  ['sunriseomelet', '🍳', 'Sunrise omelet', 'epic', 'Breakfast turned the dungeon lights on.'],
  ['shadowtruffle', '🍫', 'Shadow truffle', 'epic', 'The chocolate vanished. Your character looks innocent.'],
  ['fairyfloss', '🍭', 'Fairy cloud floss', 'epic', 'A fantasy cloud dissolved before you could name it.'],
  ['volcanopizza', '🍕', 'Volcano pizza', 'epic', 'Imaginary lava cheese. Real enthusiasm.'],
  ['glaciergelato', '🍨', 'Glacier gelato', 'epic', 'The dungeon freezer has outdone itself.'],
  ['meteorcookie', '🍪', 'Meteor cookie', 'epic', 'It landed directly in your collection.'],
  ['enchantedtea', '🍵', 'Enchanted tea', 'epic', 'Your fictional teacup offered excellent life advice.'],
  ['portalpudding', '🍮', 'Portal pudding', 'epic', 'The spoon returned from another dessert dimension.'],
  ['dragonbanquet', '🍱', 'Dragon banquet', 'legendary', 'The imaginary dragon chef finally shared the recipe.'],
  ['cosmicpizza', '🍕', 'Cosmic pizza', 'legendary', 'Every slice contains a fictional solar system.'],
  ['ambrosia', '🍯', 'Ambrosia', 'legendary', 'A mythical treat. The menu simply says wow.'],
  ['royalramen', '🍜', 'Royal ramen', 'legendary', 'The dungeon crown fits perfectly on the bowl.'],
  ['infinitycake', '🎂', 'Infinity cake', 'legendary', 'A fantasy cake with an unreasonable number of layers.'],
  ['treasurebento', '🍱', 'Treasure bento', 'legendary', 'The chest contained lunch. Best loot of the raid.'],
  ['suncroissant', '🥐', 'Sun croissant', 'legendary', 'The imaginary bakery opened at the center of a star.'],
  ['moonnectar', '🥤', 'Moon nectar', 'legendary', 'A mythical drink served with a crescent-shaped straw.'],
  ['kingdumpling', '🥟', 'King dumpling', 'legendary', 'All the other dumplings stood up respectfully.'],
  ['worldtreefruit', '🍎', 'World tree fruit', 'legendary', 'One fictional fruit from the tallest tree in the realm.'],
];
export const FOODS = Object.freeze(rows.map(([id, emoji, name, rarity, reaction]) => Object.freeze({ id, emoji, name, rarity, reaction })));
export const FOOD_BY_ID = new Map(FOODS.map(food => [food.id, food]));
