"""Refresh the bundled public-domain WEB passages from their linked source chapters.
Run manually with Python and requests; the bot never fetches text while posting.
"""
import concurrent.futures
import json
import re
from html.parser import HTMLParser
from pathlib import Path
import requests

CHAPTERS = [
    ('Psalms', 'PSA', [1, 19, 23, 27, 34, 46, 91, 100, 103, 121, 139, 145, 150]),
    ('Proverbs', 'PRO', [3, 16]), ('Isaiah', 'ISA', [40, 55]),
    ('Matthew', 'MAT', [5, 6, 7]), ('John', 'JHN', [14, 15]),
    ('Romans', 'ROM', [8, 12]), ('1 Corinthians', '1CO', [13]),
    ('Galatians', 'GAL', [5]), ('Ephesians', 'EPH', [4]),
    ('Philippians', 'PHP', [2, 4]), ('Colossians', 'COL', [3]),
    ('James', 'JAS', [1]), ('1 Peter', '1PE', [4]), ('1 John', '1JN', [4]),
]

class VerseText(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.parts, self.skip = [], 0

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if self.skip:
            if tag not in ('br', 'hr', 'img'): self.skip += 1
        elif attrs.get('class') in ('notemark', 's', 's2', 'r', 'd'):
            self.skip = 1
        elif tag in ('div', 'p', 'br'):
            self.parts.append(' ')

    def handle_endtag(self, tag):
        if self.skip: self.skip -= 1
        elif tag in ('div', 'p'): self.parts.append(' ')

    def handle_data(self, data):
        if not self.skip: self.parts.append(data)

def chapter(job):
    book, code, number = job
    page = f'{code}{number:03d}' if code == 'PSA' else f'{code}{number:02d}'
    url = f'https://ebible.org/engwebp/{page}.htm'
    response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'}, timeout=30)
    response.raise_for_status()
    html = response.content.decode('utf-8')
    chunks = re.split(r'<span class="verse" id="V(\d+)">.*?</span>', html)
    result = []
    for i in range(1, len(chunks), 2):
        fragment = re.split(r'<ul class=[\'"]tnav', chunks[i + 1])[0]
        parser = VerseText(); parser.feed(fragment)
        text = re.sub(r'\s+', ' ', ''.join(parser.parts)).strip()
        assert text and '\ufffd' not in text and len(text) < 3000, (url, chunks[i])
        result.append(dict(reference=f'{book} {number}:{chunks[i]}', text=text,
                           source=url, translation='World English Bible'))
    assert result, url
    return result

def main():
    jobs = [(book, code, n) for book, code, numbers in CHAPTERS for n in numbers]
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
        groups = list(pool.map(chapter, jobs))
    by_reference = {v['reference']: v for group in groups for v in group}
    # Retain the original 26 readings, then alternate books for daily variety.
    original = ([f'Psalms 23:{v}' for v in range(1, 7)] +
                [f'Psalms 121:{v}' for v in range(1, 9)] +
                [f'1 Corinthians 13:{v}' for v in (4, 11, 12, 13)] +
                [f'Philippians 4:{v}' for v in (4, 5, 6, 7, 8, 9, 13, 19)])
    selected = [by_reference[ref] for ref in original]
    seen = set(original)
    for offset in range(max(map(len, groups))):
        for group in groups:
            if offset >= len(group): continue
            verse = group[offset]
            if verse['reference'] not in seen:
                selected.append(verse); seen.add(verse['reference'])
            if len(selected) == 365: break
        if len(selected) == 365: break
    assert len(selected) == 365
    target = Path(__file__).resolve().parents[1] / 'src/config/faithVerses.js'
    target.write_text('// World English Bible, public domain. Source: https://ebible.org/engwebp/copyright.htm\n'
                      '// Generated by scripts/import-faith-verses.py; source wording preserved, whitespace normalized.\n'
                      'export const FAITH_VERSES = Object.freeze(' + json.dumps(selected, ensure_ascii=False, indent=2) +
                      '.map(verse => Object.freeze(verse)));\n', encoding='utf-8')
    print(f'Imported {len(selected)} unique readings from {len(jobs)} verified source chapters.')

if __name__ == '__main__': main()
